version: "3.0"

services:
  nats-server:
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

  mongodb_container:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_DATABASE: baad

  gateway:
    build:
      context: gateway/
    depends_on:
      - "nats-server"
    ports:
      - "8000:8000"
    command: npm run start

  db-micro:
    build:
      context: microservices/
    depends_on:
      - "nats-server"
    command: npm run start

volumes:
  mongodb_data_container:




